# Generated by Django 3.1.3 on 2020-11-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='release_year',
            new_name='release',
        ),
    ]
